# Generated by Django 4.1 on 2022-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.IntegerField(default=901506070, max_length=12),
            preserve_default=False,
        ),
    ]
