# Generated by Django 4.1 on 2022-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_post_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('news_image', models.ImageField(upload_to='images/')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
